---
title: "**QC metrics Peptide Reports**"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---


```{r, include=FALSE}
 Sys.setenv(RSTUDIO_PANDOC="C:/Program Files/RStudio/bin/pandoc")

``` 

```{r}
# PRIDE Cluster clusters all MS/MS spectra submitted to PRIDE Archive repository release: 2015-04
# http://www.ebi.ac.uk/pride/cluster/

# Description:The present script provides a reliable QC (Quality control) report about peptides in PRIDE Cluster.

# INPUT: The input files must be in the same directory as the script, with the names: 
# - pride_cluster_peptides_ALL.tsv 
# - pride_cluster_peptides_ALL2.tsv 
# being the file "pride_cluster_peptides_ALL2.tsv" the new release to comparee.

```

```{r, include=FALSE}
# Upload packages
packages <- c("data.table", "dplyr", "ggplot2", "stringr", "knitr", "markdown", "tidyr", "reshape2", "rmarkdown")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
    install.packages(setdiff(packages, rownames(installed.packages())))  }
 
library("data.table"); library("dplyr"); library("ggplot2"); library("stringr"); 
library("knitr"); library("markdown"); library("tidyr"); library("reshape2"); library("rmarkdown")

```

```{r, include=FALSE, cache=TRUE}
#Upload files using getwd
pride_cluster_peptides_ALL_version1  <- read.delim(file.path(getwd(),"pride_cluster_peptides_ALL.tsv"), comment.char="#")
pride_cluster_peptides_ALL_version2 <- read.delim(file.path(getwd(),"pride_cluster_peptides_ALL2_prueba.csv"), comment.char="#")

#Split of the column in PEP and CPE
new_data_frame_PEP_v1 = subset(pride_cluster_peptides_ALL_version1, PEH == 'PEP')
new_data_frame_CPE_v1 = subset(pride_cluster_peptides_ALL_version1, PEH == 'CPE')

new_data_frame_PEP_v2 = subset(pride_cluster_peptides_ALL_version2, PEH == 'PEP')
new_data_frame_CPE_v2 = subset(pride_cluster_peptides_ALL_version2, PEH == 'CPE')

```



### **Repeated Sequences Results:**  

```{r, echo=FALSE}
# Checking repeated sequences.
# Here, we call duplicated twice: first from the start of the sequence column to the 
# end and then from the end back to the start using fromLast. duplicated returns a 
# logical which is or'ed (i.e., |) so that we retrieve all the row indices that have 
# duplicates. We then subset rows of new_data_frame_PEP with respect to those. To 
# accomplish the same with more than one column so that we find all rows that have 
# duplicated values in both the sequence and modification columns, we need to select 
# those columns to pass to duplicated. This can be done using subset:

res_v1 <- new_data_frame_PEP_v1[duplicated(new_data_frame_PEP_v1$sequence) | duplicated(new_data_frame_PEP_v1$sequence, fromLast=TRUE),]
seq.mod_v1 <- subset(new_data_frame_PEP_v1, select=c("sequence","modifications"))
data_duplicate_v1 <- new_data_frame_PEP_v1[duplicated(seq.mod_v1) | duplicated(seq.mod_v1, fromLast=TRUE),]


if (length(data_duplicate_v1$sequence)== 0) {
    cat("No repeated sequences in release 1. \n")
    
} else {
    cat("Repeated sequences in release 1.\n")
    kable(data_duplicate_v1)
}

#New data: 
res_v2 <- new_data_frame_PEP_v2[duplicated(new_data_frame_PEP_v2$sequence) | duplicated(new_data_frame_PEP_v2$sequence, fromLast=TRUE),]
seq.mod_v2 <- subset(new_data_frame_PEP_v2, select=c("sequence","modifications"))
data_duplicate_v2 <- new_data_frame_PEP_v2[duplicated(seq.mod_v2) | duplicated(seq.mod_v2, fromLast=TRUE),]


if (length(data_duplicate_v2$sequence)== 0) {
    cat("No repeated sequences in release 2.\n")
    
} else {
    cat("Repeated sequences in release 1.\n \n")
    kable(data_duplicate_v2)
}

```

### **Total number of peptides:**  

```{r, echo=FALSE}
#Total number: 
cat("Release1:", length(new_data_frame_PEP_v1$sequence),"\nRelease2:", length(new_data_frame_PEP_v2$sequence),"\n")

#Conditional
if (length(new_data_frame_PEP_v1$sequence)>length(new_data_frame_PEP_v2$sequence)) {
    cat("Peptides reduced:", (length(new_data_frame_PEP_v1$sequence)-length(new_data_frame_PEP_v2$sequence)),"\n")
} else if ( length(new_data_frame_PEP_v1$sequence)<length(new_data_frame_PEP_v2$sequence)) {
    cat("Peptides increased:", (length(new_data_frame_PEP_v2$sequence)-length(new_data_frame_PEP_v1$sequence)),"\n")
} else
    cat("The number of peptides are equals \n")

```

### **Peptides with no-modification:** 

```{r, echo=FALSE}
cat("Release1:",length(new_data_frame_PEP_v1$modifications[new_data_frame_PEP_v1$modifications == "NULL"]), "\nRelease2:", length(new_data_frame_PEP_v2$modifications[new_data_frame_PEP_v2$modifications == "NULL"]))

if (length(new_data_frame_PEP_v1$modifications[new_data_frame_PEP_v1$modifications == "NULL"])>length(new_data_frame_PEP_v2$modifications[new_data_frame_PEP_v2$modifications == "NULL"])) {
    cat("Peptides with no-modification reduced:", (length(new_data_frame_PEP_v1$modifications[new_data_frame_PEP_v1$modifications == "NULL"])-length(new_data_frame_PEP_v2$modifications[new_data_frame_PEP_v2$modifications == "NULL"])))
} else if ( length(new_data_frame_PEP_v1$modifications)<length(new_data_frame_PEP_v2$modifications)) {
    cat("Peptides with no-modification increased:", (length(new_data_frame_PEP_v2$modifications[new_data_frame_PEP_v2$modifications == "NULL"])-length(new_data_frame_PEP_v1$modifications[new_data_frame_PEP_v1$modifications == "NULL"])))
} else
    cat("The number of peptides with no-modifications are equals.\n")

```


### **Peptides with modifications:** 

```{r, echo=FALSE}
cat("Release1: ",length(new_data_frame_PEP_v1$modifications[new_data_frame_PEP_v1$modifications != "NULL"]), "\nRelease2: ", length(new_data_frame_PEP_v2$modifications[new_data_frame_PEP_v2$modifications != "NULL"]))

if (length(new_data_frame_PEP_v1$modifications[new_data_frame_PEP_v1$modifications != "NULL"])>length(new_data_frame_PEP_v1$modifications[new_data_frame_PEP_v2$modifications != "NULL"])) {
    cat("Peptides with modification reduced:", (length(new_data_frame_PEP_v1$modifications[new_data_frame_PEP_v1$modifications != "NULL"])-length(new_data_frame_PEP_v2$modifications[new_data_frame_PEP_v2$modifications != "NULL"])))
} else if ( length(new_data_frame_PEP_v1$modifications)<length(new_data_frame_PEP_v2$modifications)) {
    cat("Peptides with modification increased:", (length(new_data_frame_PEP_v2$modifications[new_data_frame_PEP_v2$modifications != "NULL"])-length(new_data_frame_PEP_v1$modifications[new_data_frame_PEP_v1$modifications != "NULL"])))
} else
    cat("The number of peptides with modifications are equals.\n")

```

### **New peptides**:  

```{r, echo=FALSE, warning=FALSE}
#Create a df to make it easier
df <- new_data_frame_PEP_v1
df2 <- new_data_frame_PEP_v2

#First convert your peptide counts to numeric (they're a factor with numeric character labels, that's a bit messed up):

df$peptideNumberSpectra=as.numeric(as.character(df$peptideNumberSpectra))
df2$peptideNumberSpectra=as.numeric(as.character(df2$peptideNumberSpectra))


df_final<- df %>% 
    full_join(df2, by = c("sequence", "modifications"), suffix = c(".1", ".2")) %>%
    # Fix data to convert to character and numeric
    mutate_each(funs(as.numeric(as.character(.))), starts_with("pept")) %>%
    # See difference
    mutate(change = peptideNumberSpectra.2 - peptideNumberSpectra.1)

#How many new peptides are there  in the new release?. 
df_peptides <- df_final[is.na(df_final$PEH.1),]
df_peptides2 <- data.frame(sequences=df_peptides$sequence, modifications=df_peptides$modifications)

df_peptides3 <- df_final[is.na(df_final$PEH.2),]
df_peptides4 <- data.frame(sequences=df_peptides3$sequence, modifications=df_peptides3$modifications)

#To know if the new release has obtained new peptides. 
if (nrow(df_final[is.na(df_final$PEH.1),])!=0) {
    cat("The new release has obtained new peptides\n")
    kable(df_peptides2, padding = 0)
} else if (nrow(df_final[is.na(df_final$PEH.2),])!=0) {
    cat("The new release has lost peptides\n")
    kable(df_peptides4, padding = 0)
} else
   cat("The new release has got the same peptides\n")

```

 
### **New peptides spectra:**  

```{r, echo=FALSE, warning=FALSE, results='asis'}
df$peptideNumberSpectra=as.numeric(as.character(df$peptideNumberSpectra))
df2$peptideNumberSpectra=as.numeric(as.character(df2$peptideNumberSpectra))


df_final<- df %>% 
    full_join(df2, by = c("sequence", "modifications"), suffix = c(".1", ".2")) %>%
    # Fix data to convert to character and numeric
    mutate_each(funs(as.numeric(as.character(.))), starts_with("pept")) %>%
    # See difference
    mutate(change = peptideNumberSpectra.2 - peptideNumberSpectra.1)


df_peptides_spectra <- df_final[is.na(df_final$PEH.1),]
df_peptides_spectra2 <- data.frame(sequences=df_peptides$sequence, modifications=df_peptides$modifications, peptideNumberSpectra=df_peptides$peptideNumberSpectra.2)

df_peptides_spectra3 <- df_final[is.na(df_final$PEH.2),]
df_peptides_spectra4 <- data.frame(sequences=df_peptides$sequence, modifications=df_peptides$modifications, peptideNumberSpectra=df_peptides$peptideNumberSpectra.1)


#df_finalX = subset(final_df, change != 'NA') Remove NA from the column
df_final2 <- subset(df_final, change != 0) # Check the column change to know if there are rows. 
df_final3 <- data.frame(sequence= df_final2$sequence, modifications= df_final2$modifications, SpectraChange=df_final2$change)


if (sum(df_final2$change)!=0 && nrow(df_final[is.na(df_final$PEH.1),])!=0) {
    cat("The new peptide Spectras are:", "\n")
    print(kable(df_peptides_spectra2))
    cat("\n")
    cat("The new spectras decresed or incresed are:", "\n")
    print(kable(df_final3))
} else if (sum(df_final2$change)==0 && nrow(df_final[is.na(df_final$PEH.1),])!=0) {
    cat("The new peptide Spectras are:", "\n")
    print(kable(df_peptides_spectra2))
    cat("\n")
    cat("The rest of spectras are the same.", "\n")
} else if (sum(df_final2$change)!=0 && nrow(df_final[is.na(df_final$PEH.1),])==0) {
    cat("The are not new peptide Spectras.", "\n")    
    cat("The new spectras decresed or incresed are:\n")
    print(kable(df_final3))
} else
    cat("The number of spectras are the same", "\n")

```


### **New projects**:  

```{r, echo=FALSE, warning=FALSE, results='asis'}
df$numberProjects=as.numeric(as.character(df$numberProjects))
df2$numberProjects=as.numeric(as.character(df2$numberProjects))


df_final_project<- df %>% 
    full_join(df2, by = c("sequence", "modifications"), suffix = c(".1", ".2")) %>%
    # Fix data to convert to character and numeric
    mutate_each(funs(as.numeric(as.character(.))), starts_with("proyects")) %>%
    # See difference
    mutate(change = numberProjects.2 - numberProjects.1)


df_numberProjects <- df_final[is.na(df_final$PEH.1),]
df_numberProjects2 <- data.frame(sequences=df_numberProjects$sequence, modifications= df_numberProjects$modifications, numberProjects=df_numberProjects$numberProjects.2)

df_numberProjects3 <- df_final[is.na(df_final$PEH.2),]
df_numberProjects4 <- data.frame(sequences=df_numberProjects$sequence, modifications= df_numberProjects$modifications, numberProjects=df_numberProjects$numberProjects.1)


#df_finalX = subset(final_df, change != 'NA') Remove NA from the column
df_final2 <- subset(df_final, change != 0) # Check the column change to know if there are rows. 
df_final3 <- data.frame(sequence= df_final2$sequence, numberProjects= df_final2$numberProjects, Change=df_final2$change)



if (sum(df_final2$change) != 0 && nrow(df_final[is.na(df_final$PEH.1),])!=0 ) {
    cat("The new projects are:\n")
    print(kable(df_numberProjects2))
    cat("\n")
    cat("The new number of projects decresed or incresed are:\n")
    print(kable(df_final3))
} else if (sum(df_final2$change) == 0 && nrow(df_final[is.na(df_final$PEH.1),])!=0 ) {
    cat("The new projects are:\n")
    print(kable(df_numberProjects2))
    cat("\n")
    cat("The number of spectras are the same.\n")
} else if (sum(df_final2$change) != 0 && nrow(df_final[is.na(df_final$PEH.1),])==0 ) {
    cat("The new number of projects decresed or incresed are:\n")
    print(kable(df_final3))
} else
    cat("The number of projects are the same\n")

```

### **New clusters**

```{r, echo=FALSE, warning=FALSE, results='asis'}
df$numberClusters=as.numeric(as.character(df$numberClusters))
df2$numberClusters=as.numeric(as.character(df2$numberClusters))


df_final_clusters<- df %>% 
    full_join(df2, by = c("sequence", "modifications"), suffix = c(".1", ".2")) %>%
    # Fix data to convert to character and numeric
    mutate_each(funs(as.numeric(as.character(.))), starts_with("clusters")) %>%
    # See difference
    mutate(change = numberClusters.2 - numberClusters.1)


df_cluster <- df_final[is.na(df_final$PEH.1),]
df_cluster2 <- data.frame(sequences=df_cluster$sequence, modifications=df_cluster$modifications, numberClusters=df_cluster$numberClusters.2) 


df_cluster3 <- df_final[is.na(df_final$PEH.2),]
df_cluster4 <- data.frame(sequences=df_cluster$sequence, modifications=df_cluster$modifications, numberClusters=df_cluster$numberClusters.1) 


#df_finalX = subset(final_df, change != 'NA') Remove NA from the column
df_final2 <- subset(df_final, change != 0) # Check the column change to know if there are rows. 
df_final3 <- data.frame(sequence= df_final2$sequence, modifications= df_final2$modifications, Change=df_final2$change)



if (sum(df_final2$change) != 0 && nrow(df_final[is.na(df_final$PEH.1),])!=0 ) {
    cat("The new clusters are:\n")
    print(kable(df_cluster2))
    cat("\n")
    cat("The number of clusters decresed or incresed are:\n")
    print(kable(df_final3))
} else if (sum(df_final2$change) == 0 && nrow(df_final[is.na(df_final$PEH.1),])!=0 ) {
    cat("The new clusters are:\n")
    print(kable(df_cluster2))
    cat("\n")
    cat("The number of clusters are the same.\n")
} else if (sum(df_final2$change) != 0 && nrow(df_final[is.na(df_final$PEH.1),])==0 ) {
    cat("The number of clusters decresed or incresed are:\n")
    print(kable(df_final3))
} else
    cat("The number of clusters are the same\n")

```


### **Barplot**: 

```{r, echo=FALSE}
#HISTOGRAM: 
#Para preparar el histograma tenemos que clasificar los tipos de modificaciones, POSICION-DATABA-ID. 
# Para ello cogemos los datos que no sean NULL y eliminamos los espacios en banco. 

histo1 = subset(new_data_frame_PEP_v1, modifications != 'NULL')
histo1[histo1==""] <- NA
histo1 = subset(histo1, modifications != 'NA')

histo1_2 = subset(new_data_frame_PEP_v2, modifications != 'NULL')
histo1_2[histo1_2==""] <- NA
histo1_2 = subset(histo1_2, modifications != 'NA')

#Split dataset. 
histo2 <- data.frame(str_split_fixed(histo1$modifications, ",", 20))
histo2_2 <- data.frame(str_split_fixed(histo1_2$modifications, ",", 20))

#If you want to check how many columns are empty, you can use the code below: 
#columns_emply <- histo2[!sapply(histo2, function(x) all(x == ""))]
#columns_emply <- histo2_2[!sapply(histo2_2, function(x) all(x == ""))]

#Merge the columns in one. 
histo3 <- melt(setDT(histo2),                              # set df to a data.table
               measure.vars = list(c(1:20)),    # set column groupings
               value.name = 'V')[                      # set output name scheme
                   , -1, with = F]

histo3_2 <- melt(setDT(histo2_2),                              # set df to a data.table
                 measure.vars = list(c(1:20)),    # set column groupings
                 value.name = 'V')[                      # set output name scheme
                     , -1, with = F]

#Remove white rows.  
histo3[histo3==""] <- NA
histo3 = subset(histo3, V1 != " ")

histo3_2[histo3_2==""] <- NA
histo3_2 = subset(histo3_2, V1 != " ")

#Remove first part of the string [num]-
histo4 <- data.frame(modifications=gsub(" [A-Za-z] ", "", gsub("[0-9]*-", "", histo3$V1)))
histo4_2 <- data.frame(modifications.2=gsub(" [A-Za-z] ", "", gsub("[0-9]*-", "", histo3_2$V1)))

#Histograma: 
histo5 <- data.frame(table(histo4))
histo5_2 <- data.frame(table(histo4_2))

# ggplot(data=histo5, aes(x=histo4, y=Freq, fill=histo4)) +
#     geom_bar(stat="identity") + guides(fill=FALSE)+ 
#     theme(axis.text.x = element_text(angle = 90, hjust = 1))
# 
# ggplot(data=histo5_2, aes(x=histo4_2, y=Freq, fill=histo4_2)) +
#     geom_bar(stat="identity") + guides(fill=FALSE)+ 
#     theme(axis.text.x = element_text(angle = 90, hjust = 1))

```

```{r, echo=FALSE, warning=FALSE, fig.width=25, fig.height= 15 }
df <- cbind.data.frame(histo4_2, histo4[match(histo4_2$modifications.2, histo4$modifications), ])
colnames(df) <- c("modifications.1","modifications.2")


df2 <- melt(df,measure.vars = names(df))

ggplot((df2), aes(x = value, fill = variable)) + 
    geom_bar(stat = "count", position = "dodge") + 
    theme(axis.text.x = element_text(angle = 20, hjust = 0.5, vjust = -0.1)) + 
    guides(fill=FALSE)+
    labs("Barplot Release1 vs Release 2") + 
    xlab("Values")+
    ylab("Frequency")+
    theme(text = element_text(size=18), axis.text.x = element_text(angle = 90, hjust = 1, size = 15), axis.text.y=element_text(size = 15))
```

### **Frequency table:**
```{r, echo=FALSE, }
#Comparative table. 

df_freq1 <- data.frame(table(df$modifications.1))
df_freq2 <- data.frame(table(df$modifications.2))
colnames(df_freq1) <- c("Modifications.1", "Frequency")
colnames(df_freq2) <- c("Modifications.2", "Frequency")

df_freq3 <- cbind.data.frame(df_freq1, df_freq2[match(df_freq1$Modifications.1, df_freq2$Modifications.2), ])
kable(df_freq3, row.names = FALSE, padding = 0)


```




